name: Automated Astro Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: codeberg-gitea-medium
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Setup SSH keys for the deploy script
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host codeberg.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      # Install pnpm and dependencies
      - name: Install pnpm & Dependencies
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install

      # Execute deployment script
      - name: Build and Deploy
        run: pnpm run deploy
